name: Container
on: push

jobs:
    node-docker: 
      runs-on: ubuntu-latest
      services:
        app:
          image: alialaa17/node-api
          ports:
            - 3001:3000
        mongo:
          image: mongo
          ports:
            - "27017:27017"
      container: 
        image: node:13.5.0-alpine3.10
      steps:
        - name: Install curl
          run: sudo apt-get install curl
        - name: Print curl version
          run: curl --version
        - name: POST a user
          run: 'curl -X POST http://localhost:3001/api/user
            -H ''Content-Type: application/json'' 
            -d ''{"username": "hello", "address": "Calle 11 sur"}'''
        - name: GET a user
          run: curl http://localhost:3001/api/users