on: push
jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./Exercise1/.github/actions/hello
        with:
          who-to-greet: "World"
      - run: |
          echo "Time: ${{steps.hello.outputs.time}}"
